#!/bin/sh

# Usage ./build-key Common_Name

# Make a certificate/private key pair using a locally generated
# root certificate.

export EASY_RSA="${EASY_RSA:-.}"
export KEY_CN=$1
"$EASY_RSA/pkitool" $*

