---
# This playbook installs OpenVPN, Easy RSA2. 
# Then upgrades all installed packages.
   - name: Enable epel-release repo
     yum: name=epel-release state=present

   - name: Installing OpenVPN, Easy-RSA2
     yum: name="{{ item }}" state=present
     with_items:
     - openvpn
     - easy-rsa

   - name: Upgrade all installed packages
     yum: name="*" state=latest

