---
# This playbook installs OpenVPN, Git, and firewalld. 
# Then upgrades all installed packages.
 - hosts: vpn
   tasks:
   - name: Enable epel-release repo
     yum: name=epel-release state=present

   - name: Install firewalld, OpenVPN, easy-rsa
     yum: name="{{ item }}" state=present
     with_items:
     - openvpn
     - easy-rsa
     - firewalld

   - name: Upgrade all installed packages
     yum: name="*" state=latest

