---
# This playbook installs OpenVPN, Easy RSA2. 
# Then upgrades all installed packages.
   - name: Enable epel-release repo
     yum: name=epel-release state=present

   - name: Installing OpenVPN, Easy-RSA2
     yum: name="{{ item }}" state=present
     with_items:
     - openvpn
     - easy-rsa

   - name: Upgrade all installed packages
     yum: name="*" state=latest

   - name: Copy server.conf to /etc/openvpn/server/server.conf
     copy:
      src: "{{ role_path }}/files/server.conf"
      dest: /etc/openvpn/server/server.conf
      owner: root
      group: root
      mode: 0644
      backup: yes
      register: serverconf
   - debug:
      var: serverconf.backup_file

